.PHONY: clean All

All:
	@echo "----------Building project:[ UOCMarks - Debug ]----------"
	@"$(MAKE)" -f  "UOCMarks.mk"
clean:
	@echo "----------Cleaning project:[ UOCMarks - Debug ]----------"
	@"$(MAKE)" -f  "UOCMarks.mk" clean
