.PHONY: clean All

All:
	@echo "----------Building project:[ UOCMoney - Release ]----------"
	@cd "UOCMoney" && "$(MAKE)" -f  "UOCMoney.mk"
clean:
	@echo "----------Cleaning project:[ UOCMoney - Release ]----------"
	@cd "UOCMoney" && "$(MAKE)" -f  "UOCMoney.mk" clean
